syntax style changes

diff --git a/arkhive b/arkhive
--- a/arkhive
+++ b/arkhive
@@ -25,7 +25,7 @@
 ##      libopus
 ##      libvorbis
 ##      VobSub2SRT
-##      x265 >=1.3.x
+##      x265 >=1.5.x
 
 # VIDEO: h.265 (High Efficiency Video Coding)
 # AUDIO: AC-3 (Audio Codec 3)
@@ -74,10 +74,11 @@ path_hasbin() {
 ffmpeg_compile_option() {
 
   hasFFmpegLib=$(ffmpeg 2>&1 | grep -o "enable-${1}")
-  if [ -z "$hasFFmpegLib" ] ; then
+
+  [ -z "$hasFFmpegLib" ] && {
     echo "ERROR: FFmpeg not compiled with: '${1}'"
     return 1
-  fi
+  }
 
 }
 
@@ -228,11 +229,11 @@ else
 fi
 
 # Confirm user has provided input
-if [ -z "$userInput" ] ; then
+[ -z "$userInput" ] && {
   eval "printf \"${HELP}\""
   echo -e "${clR}ERROR: no input provided"
   exit 1
-fi
+}
 
 # Find number of cpu's (physical, not logical cores)
 export cpuCores=$(awk '/^cpu\ cores/ { print $4 ; exit }' /proc/cpuinfo | grep -o '[0-9]*')
@@ -509,11 +510,13 @@ subtitle_type() {
 subtitle_srt_converter() {
 
   # Check for VobSub and convert to SRT
-  if [ -f "$(temp_directory)/$(filename).idx" ] && [ -f "$(temp_directory)/$(filename).sub" ]; then
+  [ -f "$(temp_directory)/$(filename).idx" ] && [ -f "$(temp_directory)/$(filename).sub" ] && {
     echo "         Converting VobSub to SRT"
-    vobsub2srt $(temp_directory)/$(filename) &> /dev/null || \
-    { echo "WARNING: failed to convert vobsub to srt" ; return 1 ; }
-  fi
+    vobsub2srt $(temp_directory)/$(filename) &> /dev/null || {
+      echo "WARNING: failed to convert vobsub to srt"
+      return 1
+    }
+  }
 
 }
 
@@ -1126,8 +1129,10 @@ mux_streams() {
 cleanup_temp_file() {
 
   [ -f "$(temp_directory)/${1}" ] && {
-    rm -f $(temp_directory)/${1} || \
-    { echo "WARNING: failed to remove temp file: ${1}" ; return 1 ; }
+    rm -f $(temp_directory)/${1} || {
+      echo "WARNING: failed to remove temp file: ${1}"
+      return 1
+    }
     echo "Removed temp file: ${1}"
   }
 
@@ -1154,9 +1159,8 @@ run_arkhive() {
   input_directory "${inputFile}"
 
   # Determine if input has subtitles
-  hasSubtitles=$(\
-    ffprobe $userInput 2>&1 | \
-    awk '/Subtitle/ { print $2 }')
+  hasSubtitles=$(ffprobe $userInput 2>&1 | awk '/Subtitle/ { print $2 }')
+
   [ -n "$hasSubtitles" ] && {
     subtitle_stream_selector
     subtitle_stream_extractor
@@ -1165,9 +1169,9 @@ run_arkhive() {
   #
   # TODO: test here for non-srt subtitles
   #
-  if  [ "subtitlesNotSrt" == "true" ] ; then
+  [ "subtitlesNotSrt" == "true" ] && {
     subtitle_srt_converter
-  fi
+  }
 
   # Determine if a chapter stream exists
   hasChapters=$(ffprobe -i $userInput 2>&1 | awk '/Chapter/ { print $2 }')
